import requests
BASE_URL = "http://127.0.0.1:5000"

print("✅ Criando fornecedores...")
requests.post(f"{BASE_URL}/fornecedores", json={"nome": "Cervejaria Azul", "contato": "11987654321"})
requests.post(f"{BASE_URL}/fornecedores", json={"nome": "Vin\u00edcola S\u00e3o Jorge", "contato": "11333445566"})
requests.post(f"{BASE_URL}/fornecedores", json={"nome": "Refrescos Tropicais", "contato": "11911223344"})
requests.post(f"{BASE_URL}/fornecedores", json={"nome": "Destilaria do Vale", "contato": "11899887766"})
requests.post(f"{BASE_URL}/fornecedores", json={"nome": "Adega Imperial", "contato": "11775544332"})
requests.post(f"{BASE_URL}/fornecedores", json={"nome": "Bebidas S\u00e3o Paulo", "contato": "11666778899"})
requests.post(f"{BASE_URL}/fornecedores", json={"nome": "Cervejaria do Litoral", "contato": "11922334455"})
requests.post(f"{BASE_URL}/fornecedores", json={"nome": "Vinhos & Companhia", "contato": "11442889900"})
requests.post(f"{BASE_URL}/fornecedores", json={"nome": "Refrescos & Cia", "contato": "11555667788"})
requests.post(f"{BASE_URL}/fornecedores", json={"nome": "Destilaria Real", "contato": "11900011122"})

print("✅ Criando produtos...")
requests.post(f"{BASE_URL}/produtos", json={"nome": "Cerveja Pilsen", "descricao": "Cerveja clara e leve, perfeita para dias quentes.", "tipo": "lata", "quantidade": 10, "fornecedor_id": 1})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Cerveja IPA", "descricao": "IPA com amargor acentuado e notas c\u00edtricas.", "tipo": "garrafa", "quantidade": 20, "fornecedor_id": 2})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Vinho Tinto", "descricao": "Vinho encorpado, ideal para carnes vermelhas.", "tipo": "engradado", "quantidade": 30, "fornecedor_id": 3})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Suco de Laranja", "descricao": "Suco 100% natural, sem conservantes.", "tipo": "lata", "quantidade": 40, "fornecedor_id": 4})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Refrigerante Cola", "descricao": "Refrigerante tradicional com sabor marcante.", "tipo": "garrafa", "quantidade": 50, "fornecedor_id": 5})
requests.post(f"{BASE_URL}/produtos", json={"nome": "\u00c1gua com G\u00e1s", "descricao": "\u00c1gua gaseificada e refrescante.", "tipo": "engradado", "quantidade": 60, "fornecedor_id": 6})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Vinho Branco", "descricao": "Leve e frutado, ideal para pratos leves.", "tipo": "lata", "quantidade": 70, "fornecedor_id": 7})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Cerveja Weiss", "descricao": "Cerveja de trigo com notas de banana e cravo.", "tipo": "garrafa", "quantidade": 10, "fornecedor_id": 8})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Energ\u00e9tico Max", "descricao": "Bebida energ\u00e9tica com alta dose de cafe\u00edna.", "tipo": "engradado", "quantidade": 20, "fornecedor_id": 9})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Refrigerante Guaran\u00e1", "descricao": "Cl\u00e1ssico brasileiro com aroma de guaran\u00e1.", "tipo": "lata", "quantidade": 30, "fornecedor_id": 10})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Cerveja Stout", "descricao": "Escura, encorpada, com sabor de malte torrado.", "tipo": "garrafa", "quantidade": 40, "fornecedor_id": 1})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Suco de Uva", "descricao": "Integral e encorpado, direto do vinhedo.", "tipo": "engradado", "quantidade": 50, "fornecedor_id": 2})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Vinho Ros\u00e9", "descricao": "Colora\u00e7\u00e3o rosada, refrescante e frutado.", "tipo": "lata", "quantidade": 60, "fornecedor_id": 3})
requests.post(f"{BASE_URL}/produtos", json={"nome": "\u00c1gua T\u00f4nica", "descricao": "Sabor amargo e gaseificado, ideal para drinks.", "tipo": "garrafa", "quantidade": 70, "fornecedor_id": 4})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Cerveja Lager", "descricao": "Clara e equilibrada, muito consumida no Brasil.", "tipo": "engradado", "quantidade": 10, "fornecedor_id": 5})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Cerveja Pilsen", "descricao": "Cerveja clara e leve, perfeita para dias quentes.", "tipo": "lata", "quantidade": 20, "fornecedor_id": 6})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Cerveja IPA", "descricao": "IPA com amargor acentuado e notas c\u00edtricas.", "tipo": "garrafa", "quantidade": 30, "fornecedor_id": 7})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Vinho Tinto", "descricao": "Vinho encorpado, ideal para carnes vermelhas.", "tipo": "engradado", "quantidade": 40, "fornecedor_id": 8})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Suco de Laranja", "descricao": "Suco 100% natural, sem conservantes.", "tipo": "lata", "quantidade": 50, "fornecedor_id": 9})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Refrigerante Cola", "descricao": "Refrigerante tradicional com sabor marcante.", "tipo": "garrafa", "quantidade": 60, "fornecedor_id": 10})
requests.post(f"{BASE_URL}/produtos", json={"nome": "\u00c1gua com G\u00e1s", "descricao": "\u00c1gua gaseificada e refrescante.", "tipo": "engradado", "quantidade": 70, "fornecedor_id": 1})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Vinho Branco", "descricao": "Leve e frutado, ideal para pratos leves.", "tipo": "lata", "quantidade": 10, "fornecedor_id": 2})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Cerveja Weiss", "descricao": "Cerveja de trigo com notas de banana e cravo.", "tipo": "garrafa", "quantidade": 20, "fornecedor_id": 3})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Energ\u00e9tico Max", "descricao": "Bebida energ\u00e9tica com alta dose de cafe\u00edna.", "tipo": "engradado", "quantidade": 30, "fornecedor_id": 4})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Refrigerante Guaran\u00e1", "descricao": "Cl\u00e1ssico brasileiro com aroma de guaran\u00e1.", "tipo": "lata", "quantidade": 40, "fornecedor_id": 5})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Cerveja Stout", "descricao": "Escura, encorpada, com sabor de malte torrado.", "tipo": "garrafa", "quantidade": 50, "fornecedor_id": 6})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Suco de Uva", "descricao": "Integral e encorpado, direto do vinhedo.", "tipo": "engradado", "quantidade": 60, "fornecedor_id": 7})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Vinho Ros\u00e9", "descricao": "Colora\u00e7\u00e3o rosada, refrescante e frutado.", "tipo": "lata", "quantidade": 70, "fornecedor_id": 8})
requests.post(f"{BASE_URL}/produtos", json={"nome": "\u00c1gua T\u00f4nica", "descricao": "Sabor amargo e gaseificado, ideal para drinks.", "tipo": "garrafa", "quantidade": 10, "fornecedor_id": 9})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Cerveja Lager", "descricao": "Clara e equilibrada, muito consumida no Brasil.", "tipo": "engradado", "quantidade": 20, "fornecedor_id": 10})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Cerveja Pilsen", "descricao": "Cerveja clara e leve, perfeita para dias quentes.", "tipo": "lata", "quantidade": 30, "fornecedor_id": 1})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Cerveja IPA", "descricao": "IPA com amargor acentuado e notas c\u00edtricas.", "tipo": "garrafa", "quantidade": 40, "fornecedor_id": 2})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Vinho Tinto", "descricao": "Vinho encorpado, ideal para carnes vermelhas.", "tipo": "engradado", "quantidade": 50, "fornecedor_id": 3})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Suco de Laranja", "descricao": "Suco 100% natural, sem conservantes.", "tipo": "lata", "quantidade": 60, "fornecedor_id": 4})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Refrigerante Cola", "descricao": "Refrigerante tradicional com sabor marcante.", "tipo": "garrafa", "quantidade": 70, "fornecedor_id": 5})
requests.post(f"{BASE_URL}/produtos", json={"nome": "\u00c1gua com G\u00e1s", "descricao": "\u00c1gua gaseificada e refrescante.", "tipo": "engradado", "quantidade": 10, "fornecedor_id": 6})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Vinho Branco", "descricao": "Leve e frutado, ideal para pratos leves.", "tipo": "lata", "quantidade": 20, "fornecedor_id": 7})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Cerveja Weiss", "descricao": "Cerveja de trigo com notas de banana e cravo.", "tipo": "garrafa", "quantidade": 30, "fornecedor_id": 8})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Energ\u00e9tico Max", "descricao": "Bebida energ\u00e9tica com alta dose de cafe\u00edna.", "tipo": "engradado", "quantidade": 40, "fornecedor_id": 9})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Refrigerante Guaran\u00e1", "descricao": "Cl\u00e1ssico brasileiro com aroma de guaran\u00e1.", "tipo": "lata", "quantidade": 50, "fornecedor_id": 10})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Cerveja Stout", "descricao": "Escura, encorpada, com sabor de malte torrado.", "tipo": "garrafa", "quantidade": 60, "fornecedor_id": 1})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Suco de Uva", "descricao": "Integral e encorpado, direto do vinhedo.", "tipo": "engradado", "quantidade": 70, "fornecedor_id": 2})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Vinho Ros\u00e9", "descricao": "Colora\u00e7\u00e3o rosada, refrescante e frutado.", "tipo": "lata", "quantidade": 10, "fornecedor_id": 3})
requests.post(f"{BASE_URL}/produtos", json={"nome": "\u00c1gua T\u00f4nica", "descricao": "Sabor amargo e gaseificado, ideal para drinks.", "tipo": "garrafa", "quantidade": 20, "fornecedor_id": 4})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Cerveja Lager", "descricao": "Clara e equilibrada, muito consumida no Brasil.", "tipo": "engradado", "quantidade": 30, "fornecedor_id": 5})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Cerveja Pilsen", "descricao": "Cerveja clara e leve, perfeita para dias quentes.", "tipo": "lata", "quantidade": 40, "fornecedor_id": 6})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Cerveja IPA", "descricao": "IPA com amargor acentuado e notas c\u00edtricas.", "tipo": "garrafa", "quantidade": 50, "fornecedor_id": 7})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Vinho Tinto", "descricao": "Vinho encorpado, ideal para carnes vermelhas.", "tipo": "engradado", "quantidade": 60, "fornecedor_id": 8})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Suco de Laranja", "descricao": "Suco 100% natural, sem conservantes.", "tipo": "lata", "quantidade": 70, "fornecedor_id": 9})
requests.post(f"{BASE_URL}/produtos", json={"nome": "Refrigerante Cola", "descricao": "Refrigerante tradicional com sabor marcante.", "tipo": "garrafa", "quantidade": 10, "fornecedor_id": 10})


